<?php

/**
 * ActivationCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivationCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivationCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivationCode');
    }
}