<?php

/**
 * ArticleCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleCategory');
    }
}