# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  default_culture:   ru
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            0ef5c9ad624daeb8729f2fe03d5d63f2f0d87050

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    enabled_modules:      [default, sfGuardAuth, sfCaptchaGD]

    login_module:         sfGuardAuth
    login_action:         signin

    standard_helpers:     [Partial, Cache, I18N, Captcha]

    i18n:                 true
    culture:              ru