<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public static function getUserByCode($code)
    {
        $q = Doctrine_Query::create()
             ->select("user.*")
             ->from("sfGuardUser user, ActivationCode code")
             ->where("(user.id = code.user_id) AND (code.code = '$code')");

        return $q->fetchOne();
    }
}