<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    public function getActivationCode()
    {
        $doc_instance = ActivationCodeTable::getInstance();
        $q = $doc_instance->createQuery('c')
            ->where('c.user_id = ?', $this->getId());

        return $q->fetchOne();
    }

    public function activateWithCode()
    {
        $this->setIsActive(true);
        $this->save();

        $code = $this->getActivationCode();
        $code->delete();
    }

}
